# By default in the acl file, everything is blocked, so you have to give explicit access

# Block client_a from publishing to messages/b
user client_a
topic write playground/messages/#
# deny is considered above anything allowing access
topic deny playground/messages/b

# Allow client_b to subscribe to everything under playground/messages/
user client_b
topic read playground/messages/#
