# Mosquitto configuration for local playground

# Listen on localhost only
listener 1883 127.0.0.1
protocol mqtt

# Connections must connect with username and password
allow_anonymous false
# Passwords are stored in the password file
password_file /home/mcb/personal/mqtt_playground/broker/passwd

# Log to stdout
log_dest stdout
log_type all

acl_file /home/mcb/personal/mqtt_playground/broker/acl.conf
